import type { Metadata } from "next";
import nextFontLocal from "next/font/local";
import "./globals.css";
import { UIProvider } from "./components/LayoutWrapper";

const geistSans = nextFontLocal({
  src: "./fonts/geist-sans-variable.woff2",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = nextFontLocal({
  src: "./fonts/geist-mono-variable.woff2",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
